backend:
  name: git-gateway
  branch: main
media_folder: "public/img"
public_folder: "/img"
collections:
  - name: "image"
    label: "image"
    folder: "src/img" # The path to the folder where the documents are stored
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - {label: "image", name: "title", widget: "image"}      